version = "1.0.0"

[[pulse-trufflehog.files]]
file = "frontend/src/mocks/handlers.ts"
 
  [[pulse-trufflehog.files.secrets]]   
  type = "Password"
  values = [ "pas***********123\"" ]

[[pulse-trufflehog.files]]
file = "tests/unit/test_mcp_config.py"
 
  [[pulse-trufflehog.files.secrets]]   
  type = "URI"
  values = [ "https://user:********@server1:8080/path" ]